import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this template
*/
`;

const prod =
  process.argv.includes("production") || process.env.NODE_ENV === "production";

const jsContext = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

const cssContext = await esbuild.context({
  entryPoints: ["src/styles/plugin.css"],
  bundle: true,
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  outfile: "styles.css",
  minify: prod,
});

if (prod) {
  await Promise.all([jsContext.rebuild(), cssContext.rebuild()]);
  await Promise.all([jsContext.dispose(), cssContext.dispose()]);
  process.exit(0);
} else {
  await Promise.all([jsContext.watch(), cssContext.watch()]);
}
